/* LootRush - Real Live Wins + Online + Leaderboard + Big Win */
(function(){
  const SERVER='https://lootrush-2.onrender.com'; let source=null; const board=new Map();
  const token=()=>localStorage.getItem('lootRushToken')||'';
  const safe=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=n=>Number.isInteger(Number(n))?String(Number(n)):Number(n||0).toFixed(2);
  function ensure(){const game=document.getElementById('game');if(!game)return null;let f=document.getElementById('liveWinsFeed');if(!f){const card=game.querySelector('.page-card');if(!card)return null;f=document.createElement('aside');f.id='liveWinsFeed';f.innerHTML='<div class="live-wins-head"><span class="live-wins-title"><span class="live-dot"></span>RECENT WINS</span><span class="live-wins-badge">LIVE <span id="liveOnlineCount"></span></span></div><div id="liveWinsList"></div><div class="mini-leaderboard"><div class="mini-board-title">🏆 TOP WINNERS</div><div id="miniLeaderboard"></div></div>';game.style.position='relative';game.insertBefore(f,card)}return f}
  function render(x,isNew){const l=document.getElementById('liveWinsList');if(!l)return;const r=document.createElement('div');r.className='live-win'+(isNew?' live-win-new':'');r.innerHTML=`<div class="live-win-avatar">${safe(String(x.username||'?').charAt(0).toUpperCase())}</div><div class="live-win-main"><span class="live-win-user">${safe(x.username||'Player')}</span><span class="live-win-game">${safe(x.game||'Game')}</span></div><span class="live-win-reward">+${fmt(x.amount)} ${safe(x.currency||'💎')}</span>`;l.prepend(r);while(l.children.length>5)l.lastElementChild.remove();if(isNew&&Number(x.amount)>=25)bigWin(x)}
  function addBoard(x){const n=String(x.username||'Player'),v=board.get(n)||{username:n,total:0};v.total+=Number(x.amount)||0;board.set(n,v)}
  function boardRender(){const e=document.getElementById('miniLeaderboard');if(!e)return;const a=[...board.values()].sort((x,y)=>y.total-x.total).slice(0,3);e.innerHTML=a.length?a.map((x,i)=>`<div class="mini-board-row"><span class="mini-rank">${['🥇','🥈','🥉'][i]}</span><span class="mini-name">${safe(x.username)}</span><strong>+${fmt(x.total)} 💎</strong></div>`).join(''):'<div class="mini-empty">Waiting for winners…</div>'}
  function snapshot(w){const l=document.getElementById('liveWinsList');if(!l)return;l.innerHTML='';board.clear();(w||[]).slice().reverse().forEach(x=>{addBoard(x);render(x,false)});boardRender()}
  function online(n){const e=document.getElementById('liveOnlineCount');if(e)e.textContent=n?` • ${n} ONLINE`:''}
  function bigWin(x){let e=document.getElementById('bigWinPopup');if(!e){e=document.createElement('div');e.id='bigWinPopup';document.body.appendChild(e)}e.innerHTML=`<div class="big-win-glow">🏆</div><div><small>BIG WIN</small><strong>${safe(x.username||'Player')}</strong><span>${safe(x.game||'Game')} · +${fmt(x.amount)} ${safe(x.currency||'💎')}</span></div>`;e.classList.remove('show');void e.offsetWidth;e.classList.add('show');clearTimeout(window.__bigWinTimer);window.__bigWinTimer=setTimeout(()=>e.classList.remove('show'),3500)}
  function connect(){ensure();if(source)source.close();source=new EventSource(`${SERVER}/api/wins/stream`);source.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.type==='snapshot'){snapshot(d.wins);online(d.online)}else if(d.type==='online')online(d.online);else if(d.username){addBoard(d);render(d,true);boardRender()}}catch(err){console.warn('Live feed error',err)}};source.onerror=()=>{source.close();setTimeout(connect,5000)}}
  async function publish(game,amount,currency='💎'){const t=token(),n=Number(amount);if(!t||!Number.isFinite(n)||n<=0)return;try{await fetch(`${SERVER}/api/wins`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify({game,amount:n,currency})})}catch(e){console.warn('win publish failed',e)}}
  const coins=()=>Number(localStorage.getItem('coins'))||0,diamonds=()=>Number(localStorage.getItem('diamonds'))||0;
  function wrap(){if(window.__liveWinsWrapped)return;window.__liveWinsWrapped=true;const r=window.rollLoot;if(typeof r==='function')window.rollLoot=function(){const c=coins(),d=diamonds(),t=Number(localStorage.getItem('totalRolls'))||0,z=r.apply(this,arguments),nt=Number(localStorage.getItem('totalRolls'))||0;if(nt>t){const dc=coins()-c,dd=diamonds()-d;if(dc>0)publish('🎲 Roll',dc,'💵');else if(dd>0)publish('🎲 Roll',dd,'💎')}return z};const b=window.cashOutBomber;if(typeof b==='function')window.cashOutBomber=function(){const d=diamonds(),z=b.apply(this,arguments),g=diamonds()-d;if(g>0)publish('💣 Bomber',g,'💎');return z};const c=window.cashOutCrash;if(typeof c==='function')window.cashOutCrash=function(){const d=diamonds(),z=c.apply(this,arguments),g=diamonds()-d;if(g>0)publish('📈 Multiplier',g,'💎');return z}}
  window.publishLootRushWin=publish;function init(){ensure();connect();wrap()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();