/* LootRush - Real Live Wins + Online + Interactive Recent Wins */
(function(){
  const SERVER='https://lootrush.7st5zchchb.workers.dev'; let source=null;
  const token=()=>localStorage.getItem('lootRushToken')||'';
  const safe=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=n=>Number.isInteger(Number(n))?String(Number(n)):Number(n||0).toFixed(2);
  function ensure(){const game=document.getElementById('game');if(!game)return null;let f=document.getElementById('liveWinsFeed');if(!f){const hero=game.querySelector('.game-hero');if(!hero)return null;f=document.createElement('aside');f.id='liveWinsFeed';f.innerHTML='<div class="live-wins-head"><span class="live-wins-title"><span class="live-dot"></span>RECENT WINS</span><span class="live-wins-badge">LIVE <span id="liveOnlineCount"></span></span></div><div id="liveWinsList"></div>';game.insertBefore(f,hero)}return f}
  function gameTarget(g){const s=String(g||'').toLowerCase();if(s.includes('bomber'))return 'bomber';if(s.includes('multiplier')||s.includes('crash'))return 'crash';return 'game'}
  function render(x,isNew){const l=document.getElementById('liveWinsList');if(!l)return;const r=document.createElement('div');r.className='live-win'+(isNew?' live-win-new':'');r.tabIndex=0;r.innerHTML=`<div class="live-win-avatar">${safe(String(x.username||'?').charAt(0).toUpperCase())}</div><div class="live-win-main"><span class="live-win-user">${safe(x.username||'Player')}</span><span class="live-win-game">${safe(x.game||'Game')} · WON</span></div><span class="live-win-reward">+${fmt(x.amount)} ${safe(x.currency||'💎')}</span><div class="live-win-play">PLAY NOW ›</div>`;r.addEventListener('click',()=>{const target=gameTarget(x.game);if(typeof window.showPage==='function')window.showPage(target);if(target==='game')setTimeout(()=>{if(typeof window.rollLoot==='function')window.rollLoot()},100)});l.prepend(r);while(l.children.length>5)l.lastElementChild.remove();if(isNew&&Number(x.amount)>=25)bigWin(x)}
  function snapshot(w){const l=document.getElementById('liveWinsList');if(!l)return;l.innerHTML='';(w||[]).slice().reverse().forEach(x=>render(x,false))}
  function online(n){const e=document.getElementById('liveOnlineCount');if(e)e.textContent=n?` • ${n} ONLINE`:''}
  function bigWin(x){let e=document.getElementById('bigWinPopup');if(!e){e=document.createElement('div');e.id='bigWinPopup';document.body.appendChild(e)}e.innerHTML=`<div class="big-win-glow">🏆</div><div><small>BIG WIN</small><strong>${safe(x.username||'Player')}</strong><span>${safe(x.game||'Game')} · +${fmt(x.amount)} ${safe(x.currency||'💎')}</span></div>`;e.classList.remove('show');void e.offsetWidth;e.classList.add('show');clearTimeout(window.__bigWinTimer);window.__bigWinTimer=setTimeout(()=>e.classList.remove('show'),3500)}
  function connect(){ensure();if(source)source.close();source=new EventSource(`${SERVER}/api/wins/stream`);source.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.type==='snapshot'){snapshot(d.wins);online(d.online)}else if(d.type==='online')online(d.online);else if(d.username)render(d,true)}catch(err){console.warn('Live feed error',err)}};source.onerror=()=>{source.close();setTimeout(connect,5000)}}
  async function publish(game,amount,currency='💎'){const t=token(),n=Number(amount);if(!t||!Number.isFinite(n)||n<=0)return;try{await fetch(`${SERVER}/api/wins`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify({game,amount:n,currency}),cache:'no-store'})}catch(e){console.warn('win publish failed',e)}}
  const coins=()=>Number(localStorage.getItem('coins'))||0,diamonds=()=>Number(localStorage.getItem('diamonds'))||0;
  function progressWin(rare){if(typeof window.lootRushTrackWin==='function')window.lootRushTrackWin(!!rare)}
  function wrap(){if(window.__liveWinsWrapped)return;window.__liveWinsWrapped=true;const r=window.rollLoot;if(typeof r==='function')window.rollLoot=function(){const c=coins(),d=diamonds(),t=Number(localStorage.getItem('totalRolls'))||0,z=r.apply(this,arguments),nt=Number(localStorage.getItem('totalRolls'))||0;if(nt>t){const dc=coins()-c,dd=diamonds()-d;if(dc>0||dd>0){publish('🎲 Roll',dc>0?dc:dd,dc>0?'💵':'💎');progressWin(dd>0)}}return z};const b=window.cashOutBomber;if(typeof b==='function')window.cashOutBomber=function(){const d=diamonds(),z=b.apply(this,arguments),g=diamonds()-d;if(g>0){publish('💣 Bomber',g,'💎');progressWin(false)}return z};const c=window.cashOutCrash;if(typeof c==='function')window.cashOutCrash=function(){const d=diamonds(),z=c.apply(this,arguments),g=diamonds()-d;if(g>0){publish('📈 Multiplier',g,'💎');progressWin(false)}return z}}
  window.publishLootRushWin=publish;function init(){ensure();connect();wrap()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();