/* LootRush Progression: Daily + Weekly Rewards */
(function(){
const XP='lootRushXP',LV='lootRushLevel',MD='lootRushMissionData',DB='lootRushDailyBonus';
const missions=[{id:'rolls10',title:'Roll 10 times',icon:'🎲',target:10,reward:400,type:'rolls',cur:'🪙'},{id:'wins3',title:'Win 3 rewards',icon:'🏆',target:3,reward:400,type:'wins',cur:'🪙'},{id:'rare1',title:'Find 1 Rare+ item',icon:'💎',target:1,reward:400,type:'rare',cur:'🪙'},{id:'follow',title:'Follow LootRush',icon:'❤️',target:1,reward:400,type:'follow',cur:'🪙'},{id:'invite',title:'Invite 1 friend',icon:'👥',target:1,reward:400,type:'invite',cur:'🪙'}];
const num=k=>Number(localStorage.getItem(k))||0,today=()=>new Date().toISOString().slice(0,10);
function weekKey(){const d=new Date(),x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())),n=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()-n+1);return x.toISOString().slice(0,10)}
let xp=num(XP),level=Math.max(1,num(LV)||1),data={};try{data=JSON.parse(localStorage.getItem(MD))||{}}catch(e){}
function save(){localStorage.setItem(MD,JSON.stringify(data))}
function reset(){const d=today(),w=weekKey();if(data.date!==d){data={...data,date:d,rolls:0,wins:0,rare:0,follow:0,invite:0,claimed:{}}}if(data.week!==w){data.week=w, data.weekRolls=0,data.weekWins=0,data.weekClaimed=false}save()}
function required(){return 100+(level-1)*50}
function reward(c){localStorage.setItem('coins',String(num('coins')+c));window.__lootrushAddCoins?.(c);window.dispatchEvent(new Event('progressReward'));window.updateAllUI?.()}
function render(){const h=document.getElementById('progressionPanel');if(!h)return;const req=required(),pct=Math.min(100,Math.round(xp/req*100)),wr=Math.min(data.weekRolls||0,50),ww=Math.min(data.weekWins||0,15),wp=Math.round(((wr/50)+(ww/15))*50);h.innerHTML=`<div class="prog-head"><div><span class="prog-kicker">PLAYER PROGRESSION</span><h2>⚡ Level ${level}</h2></div><div class="prog-xp">${xp} / ${req} XP</div></div><div class="xp-track"><i style="width:${pct}%"></i></div><div class="prog-missions"><div class="missions-title">🎯 DAILY MISSIONS <span>resets daily</span></div>${missions.map(m=>{const v=Math.min(data[m.type]||0,m.target),done=v>=m.target,claimed=!!data.claimed?.[m.id];return `<div class="mission ${done?'done':''}"><div class="mission-icon">${m.icon}</div><div class="mission-main"><strong>${m.title}</strong><small>${v} / ${m.target}</small><div class="mission-track"><i style="width:${Math.min(100,v/m.target*100)}%"></i></div></div><button data-mission="${m.id}" ${!done||claimed?'disabled':''}>${claimed?'CLAIMED':`+${m.reward} ${m.cur}`}</button></div>`}).join('')}</div><div class="weekly-reward-card ${wr>=50&&ww>=15?'weekly-ready':''}"><div><span class="prog-kicker">WEEKLY REWARD</span><h3>🏆 Weekly Champion</h3><small>50 Rolls + 15 Wins · resets Monday</small><div class="weekly-track"><i style="width:${wp}%"></i></div><small>${wr}/50 Rolls · ${ww}/15 Wins</small></div><button id="claimWeekly" ${wr<50||ww<15||data.weekClaimed?'disabled':''}>${data.weekClaimed?'CLAIMED':'+2,000 🪙'}</button></div>`;h.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>claim(b.dataset.mission));h.querySelector('#claimWeekly')?.addEventListener('click',claimWeekly)}
function addXP(n){xp+=n;while(xp>=required()){xp-=required();level++;const t=document.createElement('div');t.className='levelup-toast';t.innerHTML=`<span>⚡ LEVEL UP!</span><strong>Level ${level}</strong>`;document.body.appendChild(t);setTimeout(()=>t.remove(),2600)}localStorage.setItem(XP,String(xp));localStorage.setItem(LV,String(level));render()}
function claim(id){reset();const m=missions.find(x=>x.id===id);if(!m||data.claimed?.[id]||(data[m.type]||0)<m.target)return;data.claimed[id]=true;reward(m.reward);addXP(50);save();render()}
function claimWeekly(){reset();if((data.weekRolls||0)<50||(data.weekWins||0)<15||data.weekClaimed)return;data.weekClaimed=true;reward(2000);addXP(250);save();render();alert('🏆 Weekly Reward claimed! +2,000 🪙 +250 XP')}
function trackRoll(){reset();data.rolls++;data.weekRolls=(data.weekRolls||0)+1;addXP(5);save()}
function trackWin(rare){reset();data.wins++;data.weekWins=(data.weekWins||0)+1;if(rare)data.rare++;addXP(15);save()}
function daily(){reset();if(localStorage.getItem(DB)===today()){alert('🎁 Daily Bonus already claimed today!');return}localStorage.setItem(DB,today());reward(400);addXP(25);alert('🎁 Daily Bonus claimed! +400 🪙 +25 XP')}
function markFollow(){reset();data.follow=1;save();render()}function invite(){navigator.clipboard?.writeText(location.href);reset();data.invite=1;save();render();alert('👥 Invite link copied!')}
function init(){reset();const game=document.getElementById('game');if(game&&!document.getElementById('progressionPanel')){const p=document.createElement('div');p.id='progressionPanel';game.appendChild(p)}render();const btn=document.querySelector('#rewards .reward-box .main-button');if(btn)btn.onclick=daily;const original=window.rollLoot;if(typeof original==='function'&&!window.__progressRoll){window.__progressRoll=true;window.rollLoot=function(){const before=num('totalRolls'),r=original.apply(this,arguments);if(num('totalRolls')>before)trackRoll();return r}}}
window.lootRushTrackWin=trackWin;window.lootRushTrackRare=()=>trackWin(true);window.lootRushProgress={get level(){return level},get xp(){return xp},markFollow,invite};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init()})();