require("dotenv").config();
const express = require("express");
const cors = require("cors");
const Stripe = require("stripe");
const crypto = require("crypto");
const { Pool } = require("pg");
const path = require("path");
const app = express();
const PORT = Number(process.env.PORT) || 3000;
const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY || "";
const STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET || "";
const SESSION_SECRET = process.env.SESSION_SECRET || "";
const DATABASE_URL = process.env.DATABASE_URL || "";
const FRONTEND_URL = process.env.FRONTEND_URL || "https://7st5zchchb-collab.github.io/LootRush";
const RESEND_API_KEY = process.env.RESEND_API_KEY || "";
const EMAIL_FROM = process.env.EMAIL_FROM || "LootRush <onboarding@resend.dev>";
if (!DATABASE_URL || !SESSION_SECRET) console.error("❌ Render configuration missing: DATABASE_URL and SESSION_SECRET are required.");
const stripe = STRIPE_SECRET_KEY ? Stripe(STRIPE_SECRET_KEY) : null;
const pool = DATABASE_URL ? new Pool({ connectionString: DATABASE_URL, ssl: { rejectUnauthorized: false } }) : null;
const liveClients = new Set(); const recentWins = []; const MAX_RECENT_WINS = 30;
function broadcastWin(win){const payload=`data: ${JSON.stringify(win)}\n\n`;for(const client of liveClients){try{client.res.write(payload)}catch{liveClients.delete(client)}}}
function rememberWin(win){recentWins.unshift(win);if(recentWins.length>MAX_RECENT_WINS)recentWins.length=MAX_RECENT_WINS;broadcastWin(win)}
const PRODUCTS={diamonds_1:{name:"1 Diamond",diamonds:1,priceCents:99},diamonds_10:{name:"10 Diamonds",diamonds:10,priceCents:900},diamonds_50:{name:"50 Diamonds",diamonds:50,priceCents:3999},diamonds_100:{name:"100 Diamonds",diamonds:100,priceCents:6999},diamonds_250:{name:"250 Diamonds",diamonds:250,priceCents:14999},diamonds_500:{name:"500 Diamonds",diamonds:500,priceCents:24999},diamonds_1000:{name:"1000 Diamonds",diamonds:1000,priceCents:39999}};
app.use(cors({origin:["https://7st5zchchb-collab.github.io","http://127.0.0.1:5500","http://localhost:5500"],methods:["GET","POST","OPTIONS"],allowedHeaders:["Content-Type","Authorization","Stripe-Signature"]}));
function requireDatabase(res){if(!pool){res.status(503).json({error:"Server database is not configured. Add DATABASE_URL in Render."});return false}return true}
function requireSessionSecret(res){if(!SESSION_SECRET){res.status(503).json({error:"Server session is not configured. Add SESSION_SECRET in Render."});return false}return true}
function requireStripe(res){if(!stripe){res.status(503).json({error:"Stripe is not configured. Add STRIPE_SECRET_KEY in Render."});return false}return true}
function hashPassword(password,salt=crypto.randomBytes(16).toString("hex")){return new Promise((resolve,reject)=>crypto.scrypt(password,salt,64,(err,key)=>err?reject(err):resolve(`${salt}:${key.toString("hex")}`)))}
function verifyPassword(password,stored){return new Promise((resolve,reject)=>{const [salt,hash]=String(stored).split(":");crypto.scrypt(password,salt,64,(err,key)=>{if(err)return reject(err);const a=Buffer.from(hash,"hex"),b=key;resolve(a.length===b.length&&crypto.timingSafeEqual(a,b))})})}
function signToken(accountId){const payload=Buffer.from(JSON.stringify({id:accountId,exp:Date.now()+7*24*60*60*1000})).toString("base64url");const sig=crypto.createHmac("sha256",SESSION_SECRET).update(payload).digest("base64url");return `${payload}.${sig}`}
function getAccountId(req){if(!SESSION_SECRET)return null;const auth=String(req.headers.authorization||"");if(!auth.startsWith("Bearer "))return null;const [payload,sig]=auth.slice(7).split(".");if(!payload||!sig)return null;const expected=crypto.createHmac("sha256",SESSION_SECRET).update(payload).digest("base64url");if(sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;try{const data=JSON.parse(Buffer.from(payload,"base64url").toString("utf8"));return data.exp>Date.now()?data.id:null}catch{return null}}
async function sendVerificationEmail(email,username,rawToken){
  if(!RESEND_API_KEY) throw new Error("Email service is not configured. Add RESEND_API_KEY in Render.");
  const verifyUrl=`${FRONTEND_URL}/?verify_email=${encodeURIComponent(rawToken)}`;
  const html=`<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;padding:32px;background:#09090d;color:#fff;border-radius:16px"><h1 style="color:#ff174f">LootRush</h1><h2>Verify your email</h2><p>Hello ${String(username).replace(/[<>&\"]/g,"")},</p><p>Thanks for registering. Click the button below to verify your email address and activate your LootRush account.</p><p><a href="${verifyUrl}" style="display:inline-block;padding:14px 22px;background:#ff174f;color:#fff;text-decoration:none;border-radius:10px;font-weight:bold">Verify Email</a></p><p style="color:#aaa">This link expires in 24 hours.</p></div>`;
  const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{"Authorization":`Bearer ${RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:EMAIL_FROM,to:[email],subject:"Verify your LootRush account",html})});
  if(!response.ok){const text=await response.text();throw new Error(`Email provider error: ${text}`)}
}
app.post("/stripe-webhook",express.raw({type:"application/json"}),async(req,res)=>{if(!stripe||!STRIPE_WEBHOOK_SECRET||!pool)return res.status(503).send("Stripe webhook is not configured");let event;try{event=stripe.webhooks.constructEvent(req.body,req.headers["stripe-signature"],STRIPE_WEBHOOK_SECRET)}catch(err){return res.status(400).send("Invalid signature")}try{if(event.type==="checkout.session.completed"||event.type==="checkout.session.async_payment_succeeded"){const session=event.data.object;if(session.payment_status!=="paid")return res.json({received:true});const accountId=session.metadata?.accountId,productId=session.metadata?.productId,product=PRODUCTS[productId],paymentId=typeof session.payment_intent==="string"?session.payment_intent:session.id;if(!accountId||!product||!paymentId)return res.status(400).send("Missing payment metadata");const client=await pool.connect();try{await client.query("BEGIN");const duplicate=await client.query("SELECT id FROM payments WHERE stripe_payment_id=$1 FOR UPDATE",[paymentId]);if(duplicate.rowCount===0){const user=await client.query("SELECT id FROM users WHERE id=$1 FOR UPDATE",[accountId]);if(user.rowCount!==1)throw new Error("Account not found");await client.query("UPDATE users SET diamonds=diamonds+$1, updated_at=NOW() WHERE id=$2",[product.diamonds,accountId]);await client.query("INSERT INTO payments (stripe_payment_id,account_id,product_id,diamonds,amount_cents,currency) VALUES ($1,$2,$3,$4,$5,$6)",[paymentId,accountId,productId,product.diamonds,session.amount_total||product.priceCents,session.currency||"usd"])}await client.query("COMMIT")}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}return res.json({received:true})}catch(err){return res.status(500).send("Webhook processing failed")}});
app.use(express.json());
app.get("/api/wins/stream",(req,res)=>{res.writeHead(200,{"Content-Type":"text/event-stream","Cache-Control":"no-cache, no-transform","Connection":"keep-alive","X-Accel-Buffering":"no"});res.write(`data: ${JSON.stringify({type:"snapshot",wins:recentWins,online:liveClients.size})}\n\n`);const client={res};liveClients.add(client);res.write(`data: ${JSON.stringify({type:"online",online:liveClients.size})}\n\n`);const heartbeat=setInterval(()=>{try{res.write(": heartbeat\n\n")}catch{}},20000);const close=()=>{clearInterval(heartbeat);liveClients.delete(client)};req.on("close",close);res.on("close",close)});
app.get("/api/online",(req,res)=>res.json({success:true,online:liveClients.size}));
app.post("/api/wins",async(req,res)=>{if(!requireDatabase(res)||!requireSessionSecret(res))return;const accountId=getAccountId(req);if(!accountId)return res.status(401).json({error:"Login required."});try{const user=await pool.query("SELECT id,username FROM users WHERE id=$1",[accountId]);if(user.rowCount!==1)return res.status(401).json({error:"Account not found."});const game=String(req.body.game||"").trim().slice(0,30),amount=Number(req.body.amount),currency=String(req.body.currency||"💎").slice(0,4);if(!game||!Number.isFinite(amount)||amount<=0||amount>1000000)return res.status(400).json({error:"Invalid win."});const win={id:crypto.randomUUID(),username:user.rows[0].username,game,amount:Number(amount.toFixed(2)),currency,createdAt:Date.now()};rememberWin(win);res.json({success:true,win})}catch(err){res.status(500).json({error:"Unable to publish win."})}});
app.use(express.static(path.join(__dirname),{index:"index.html"}));app.get("/",(req,res)=>res.sendFile(path.join(__dirname,"index.html")));
app.get("/health",async(req,res)=>{const checks={database:Boolean(pool),session:Boolean(SESSION_SECRET),stripe:Boolean(stripe),webhook:Boolean(STRIPE_WEBHOOK_SECRET),email:Boolean(RESEND_API_KEY)};if(!pool)return res.status(503).json({success:false,status:"unhealthy",checks});try{await pool.query("SELECT 1");res.json({success:true,status:"healthy",checks})}catch(err){res.status(503).json({success:false,status:"unhealthy",checks,error:"Database connection failed"})}});
app.post("/register",async(req,res)=>{if(!requireDatabase(res)||!requireSessionSecret(res))return;try{const username=String(req.body.username||"").trim(),email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||"");if(username.length<3||!email.includes("@")||password.length<6)return res.status(400).json({error:"Username, valid email and 6+ character password required."});const hash=await hashPassword(password);const rawToken=crypto.randomBytes(32).toString("hex"),tokenHash=crypto.createHash("sha256").update(rawToken).digest("hex");const expires=new Date(Date.now()+24*60*60*1000);const r=await pool.query("INSERT INTO users (username,email,password_hash,email_verified,verification_token_hash,verification_expires_at) VALUES ($1,$2,$3,FALSE,$4,$5) RETURNING id,username,email,coins,diamonds,points",[username,email,hash,tokenHash,expires]);try{await sendVerificationEmail(email,username,rawToken)}catch(emailErr){await pool.query("DELETE FROM users WHERE id=$1",[r.rows[0].id]);console.error("Verification email failed:",emailErr);return res.status(503).json({error:"Account was not created because the verification email could not be sent."})}res.json({success:true,verificationRequired:true,message:"Check your email to verify your LootRush account."})}catch(err){if(err.code==="23505")return res.status(409).json({error:"Email already registered."});res.status(500).json({error:"Registration failed."})}});
app.get("/verify-email",async(req,res)=>{const raw=String(req.query.token||"");if(!raw)return res.redirect(`${FRONTEND_URL}/?verification=invalid`);const hash=crypto.createHash("sha256").update(raw).digest("hex");try{const r=await pool.query("UPDATE users SET email_verified=TRUE,verification_token_hash=NULL,verification_expires_at=NULL,updated_at=NOW() WHERE verification_token_hash=$1 AND verification_expires_at>NOW() RETURNING id",[hash]);return res.redirect(`${FRONTEND_URL}/?verification=${r.rowCount===1?"success":"invalid"}`)}catch{return res.redirect(`${FRONTEND_URL}/?verification=invalid`)}});
app.post("/resend-verification",async(req,res)=>{if(!requireDatabase(res))return;const email=String(req.body.email||"").trim().toLowerCase();try{const r=await pool.query("SELECT id,username FROM users WHERE email=$1 AND email_verified=FALSE",[email]);if(r.rowCount!==1)return res.json({success:true,message:"If the account needs verification, a new email has been sent."});const rawToken=crypto.randomBytes(32).toString("hex"),tokenHash=crypto.createHash("sha256").update(rawToken).digest("hex");await pool.query("UPDATE users SET verification_token_hash=$1,verification_expires_at=$2 WHERE id=$3",[tokenHash,new Date(Date.now()+24*60*60*1000),r.rows[0].id]);await sendVerificationEmail(email,r.rows[0].username,rawToken);res.json({success:true,message:"Verification email sent."})}catch(err){res.status(503).json({error:"Unable to send verification email."})}});
app.post("/login",async(req,res)=>{if(!requireDatabase(res)||!requireSessionSecret(res))return;try{const email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||""),r=await pool.query("SELECT * FROM users WHERE email=$1",[email]);if(r.rowCount!==1||!(await verifyPassword(password,r.rows[0].password_hash)))return res.status(401).json({error:"Wrong email or password."});const u=r.rows[0];if(!u.email_verified)return res.status(403).json({error:"Please verify your email before signing in."});res.json({success:true,token:signToken(u.id),user:{id:u.id,username:u.username,email:u.email,coins:u.coins,diamonds:u.diamonds,points:u.points}})}catch(err){res.status(500).json({error:"Login failed."})}});
app.get("/me",async(req,res)=>{if(!requireDatabase(res)||!requireSessionSecret(res))return;const id=getAccountId(req);if(!id)return res.status(401).json({error:"Unauthorized"});try{const r=await pool.query("SELECT id,username,email,coins,diamonds,points FROM users WHERE id=$1",[id]);if(r.rowCount!==1)return res.status(401).json({error:"Account not found"});res.json({success:true,user:r.rows[0]})}catch{res.status(500).json({error:"Unable to load account."})}});
app.post("/sync-progress",async(req,res)=>{if(!requireDatabase(res)||!requireSessionSecret(res))return;const id=getAccountId(req);if(!id)return res.status(401).json({error:"Unauthorized"});const coins=Math.max(0,Math.min(2147483647,Math.floor(Number(req.body.coins)||0))),diamonds=Math.max(0,Math.min(2147483647,Math.floor(Number(req.body.diamonds)||0))),points=Math.max(0,Math.min(2147483647,Math.floor(Number(req.body.points)||0)));try{const r=await pool.query("UPDATE users SET coins=$1,diamonds=$2,points=$3,updated_at=NOW() WHERE id=$4 RETURNING id,username,email,coins,diamonds,points",[coins,diamonds,points,id]);if(r.rowCount!==1)return res.status(404).json({error:"Account not found"});res.json({success:true,user:r.rows[0]})}catch(err){console.error("Progress sync error:",err);res.status(500).json({error:"Unable to save progress."})}});
app.post("/create-checkout-session",async(req,res)=>{if(!requireDatabase(res)||!requireSessionSecret(res)||!requireStripe(res))return;try{const accountId=getAccountId(req),productId=String(req.body.productId||""),product=PRODUCTS[productId];if(!accountId)return res.status(401).json({error:"Login required."});if(!product)return res.status(400).json({error:"Unknown product."});const account=await pool.query("SELECT email FROM users WHERE id=$1",[accountId]);if(account.rowCount!==1)return res.status(401).json({error:"Account not found."});const session=await stripe.checkout.sessions.create({mode:"payment",payment_method_types:["card"],line_items:[{price_data:{currency:"usd",product_data:{name:product.name,description:`${product.diamonds} LootRush Diamonds`},unit_amount:product.priceCents},quantity:1}],customer_email:account.rows[0].email,success_url:`${FRONTEND_URL}/?payment=success&session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${FRONTEND_URL}/?payment=cancel`,metadata:{accountId:String(accountId),productId}});res.json({success:true,url:session.url})}catch(err){res.status(500).json({error:"Unable to create checkout session."})}});
app.get("/payment-status",async(req,res)=>{if(!requireDatabase(res)||!requireSessionSecret(res)||!requireStripe(res))return;try{const accountId=getAccountId(req),sessionId=String(req.query.session_id||"");if(!accountId||!sessionId||!sessionId.startsWith("cs_"))return res.status(400).json({error:"Invalid request."});const session=await stripe.checkout.sessions.retrieve(sessionId);if(String(session.metadata?.accountId)!==String(accountId))return res.status(403).json({error:"Payment does not belong to this account."});res.json({success:true,paid:session.payment_status==="paid",status:session.status,sessionId:session.id})}catch(err){res.status(500).json({error:"Unable to check payment."})}});
async function initDb(){if(!pool)return;await pool.query(`CREATE EXTENSION IF NOT EXISTS pgcrypto`);await pool.query(`CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), username TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, coins INTEGER NOT NULL DEFAULT 150, diamonds INTEGER NOT NULL DEFAULT 0, points INTEGER NOT NULL DEFAULT 0, email_verified BOOLEAN NOT NULL DEFAULT FALSE, verification_token_hash TEXT, verification_expires_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`);await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE`);await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_token_hash TEXT`);await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_expires_at TIMESTAMPTZ`);await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW()`);await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW()`);await pool.query(`CREATE TABLE IF NOT EXISTS payments (id BIGSERIAL PRIMARY KEY, stripe_payment_id TEXT UNIQUE NOT NULL, account_id UUID NOT NULL REFERENCES users(id), product_id TEXT NOT NULL, diamonds INTEGER NOT NULL, amount_cents INTEGER NOT NULL, currency TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW())`)}
initDb().then(()=>app.listen(PORT,"0.0.0.0",()=>console.log(`🚀 LootRush server running on ${PORT}`))).catch(err=>{console.error("❌ Database initialization failed:",err);process.exit(1)});
